### ISSUE TITLE
Support for native kafka

### ISSUE THREAD

**Issue by patpatpat123** [toilacube/Docker-setup-for-Kafka-Kraft-mode-#1]
Hello there,

First of all, a big THANK for this project.
It is very cool, easy to use.

Just wanted to reach out with a small enhancement request.
Kafka just released a "native-kaka", based on native image.
It has been proven quite performant.

Would it be possible for this project to support a native kafka Kraft?

Thank you

**Comment by toilacube** [comment]
Hey, thanks for reach out. This repo is just a very beginner setup and I am also a newbie in the message queue world. 

I do a litte [search](https://education.github.com/pack/offers) and see that this native-kafka is just like a smaller docker image for kafka, and it said that "image is well-suited for non-production development and testing scenarios" so I dont think this would be an enhancement.

If you want to use the native kafka image, I suggest just change the image `apache/kafka` to `apache/kafka-native` in the docker compose file and then you are done.

**Comment by patpatpat123** [comment]
THanks!
